services:
  dmarket-bot:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./config:/app/config
      - ./.env:/app/.env
    environment:
      - FLASK_APP=dashboard/app.py
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped